### ISSUE TITLE
Muuri implementation 

### ISSUE THREAD

**Issue by HerveDavid** [GazePlay/AugCom#51]
[Muuri](https://haltu.github.io/muuri/) is js library for display grid elements and drag n drop.

For easily implementation,  2 new components were created:
* Grid for the behavior of the grid ( permutation list.. )
* Tile, an element of grid with  own behavior ( edit...)

The issue is to create these components from the keyboard component.

**Comment by HerveDavid** [comment]
## BoardService
**ERROR TypeError: "element.ElementForms is undefined"**

How to use the `boardService` (with initialization and getter) to obtains the data from an element?

## Pass boolean to grid component
```html
<app-grid [dragNdrop]="this.userToolBarService.edit" [elements]="this.getTempList()"></app-grid>
```

Only this method works to enabled or disabled drag and drop in grid component:

```html
<app-grid [dragNdrop]="true" [elements]="this.getTempList()"></app-grid>
<app-grid [dragNdrop]="false" [elements]="this.getTempList()"></app-grid>
```

However passing `this.getTempList()` seems to work

## Services from keyboard component

```typescript
public dragulaService: DragulaService,
public searchService: SearchService,
private router: Router,
public parametersService: ParametersService,
public indexeddbaccessService: IndexeddbaccessService,
public userToolBarService: UsertoolbarService,
public getIconService: GeticonService,
public boardService: BoardService,
public historicService: HistoricService,
public editionService: EditionService
````
Which one is useful for grid and tile separately?

**Comment by HerveDavid** [comment]
stumble upon (angular-gridster2)[https://tiberiuzuld.github.io/angular-gridster2/]

**Comment by HerveDavid** [comment]
# Resolutions

## BoardService issue 
```html
<app-tile [element]=elt></app-tile>
````
instead
```html
<app-tile element={{elt}}></app-tile>
````
## Pass boolean to grid component

Resolved by using `UsertoolbarService` in directly in the app-grid.

**Comment by HerveDavid** [comment]
## Get url in tile component
```html
this.boardService.getImgUrl(element)
```
This method returns `SafeValue must use [property]=binding:url(...)`

So how to use correctly this getter from BoardService?

## No scrolling in keyboard component
Scrolling is disabled probably due to muuri css.

## Saving the grid
When you switch off the edit mode, the grid returns to the old layout.
Even when you want to edit a tile.

**Comment by HerveDavid** [comment]
# Saving grid
When you toggle edit mode, the grid unsaved the state.
In addition, the initialization of the grid is not stable.

## The current solution
```typescript
 ngOnChanges(): void {
    this.zone.runOutsideAngular(() =>
      setTimeout(() => {
        this.grid.destroy();
        this.grid = new Muuri(".grid", {
          dragEnabled: this.userToolbarService.edit,
          layoutEasing: "cubic-bezier(0.215, 0.61, 0.355, 1)",
        });
      })
    );
  }
```
`NgZone` with `setTimeout()` works very well to initialize the grid at the beginning and switch to edit mode.
However, the grid layout is not saved. And, we can use `this.grid` in `setTimeout()`
This implementation is in `ngOnChanges()`, only in this lifecyle hook seems to work.

## Issue
This issue is to save correctly the grid with the good behaviour.

### Possibilies:
- Implements `new Muuri(".grid")` in other [lifecyle hooks](https://angular.io/guide/lifecycle-hooks)
- Find a setter for [dragEnabled](https://github.com/haltu/muuri#dragenabled-) in Muuri or a alternative
- In the 'setTimeout()' grab all items in current grid

I tried these possibilities and I try to find a other. Personally, I prefer to use a setter directly in Murri because in current solution we recreate a Murri object each time we toggle the edit mode,  which can cause problems.

## Code of gridComponent
grid.component.ts
```typescript
export class GridComponent implements OnInit, OnChanges {
  @Input() elements: Element[];

  grid: any;
  items: any;

  constructor(
    private zone: NgZone,
    private indexeddbaccessService: IndexeddbaccessService,
    public userToolbarService: UsertoolbarService
  ) {
    Muuri.defaultOptions.dragSortPredicate.action = "swap";
  }

  ngOnInit(): void {
    this.indexeddbaccessService.init();
    this.grid = new Muuri(".grid");
  }

  ngOnChanges(): void {
    this.zone.runOutsideAngular(() =>
      setTimeout(() => {
        this.grid.destroy();
        this.grid = new Muuri(".grid", {
          dragEnabled: this.userToolbarService.edit,
          layoutEasing: "cubic-bezier(0.215, 0.61, 0.355, 1)",
        });
      })
    );
  }
}
```

grid.component.html
```html
<div class="grid">
  <div class="item" *ngFor="let elt of elements">
    <div class="item-content">
      <app-tile [element]=elt></app-tile>
    </div>
  </div>
</div>
```

**Comment by kuhlkrein** [comment]
```
import {
  Component,
  OnInit,
  NgZone,
  Input,
  OnChanges,
  DoCheck,
} from "@angular/core";
import { Element } from "../../types";
import { UsertoolbarService } from "../../services/usertoolbar.service";
import { IndexeddbaccessService } from "../../services/indexeddbaccess.service";
import * as Muuri from "muuri";

@Component({
  selector: "app-grid",
  templateUrl: "./grid.component.html",
  styleUrls: ["./grid.component.css"],
})
export class GridComponent implements OnInit, OnChanges {
  @Input() elements: Element[];

  grid: any;


  constructor(
    private zone: NgZone,
    private indexeddbaccessService: IndexeddbaccessService,
    public userToolbarService: UsertoolbarService
  ) {
    Muuri.defaultOptions.dragSortPredicate.action = "swap";
  }

  ngOnInit(): void {
      setTimeout(() => {
        this.grid = new Muuri(".grid",
          {
            layoutEasing: "cubic-bezier(0.215, 0.61, 0.355, 1)",
            dragEnabled: true,
            dragStartPredicate: (item, e) => this.checkIfEditEnabled(item, e)
          });
      },2000);
    this.indexeddbaccessService.init();
  }

  checkIfEditEnabled(item,e){
    console.log("check");
    return this.userToolbarService.edit ? Muuri.ItemDrag.defaultStartPredicate(item, e) : false;
  }

  ngOnChanges(): void {
  }


}

```

**Comment by kuhlkrein** [comment]
Il faut juste que tu vois comment remédier au problème du timeout, le mieux serait d'essayer d'attendre le chargement des images, mais ça pose un soucis si certaines ne chargent pas completement ...

**Comment by HerveDavid** [comment]
Go to #15
